
export const isLogedin = async (req, res, next) => {
  try {
    
  } catch (error) {
    console.log("authentication failed ",error.message);
  }
}

export const isAdmin = async (req, res, next) => {
  try {
    
  } catch (error) {
    console.log("authentication failed ",error.message);
  }
}